hou.hscript("Redshift_setLogLevel -L 5")
hou.hipFile.load("D:/HoudiniRender/test1.hiplc")
mantra = hou.node("/obj/render/rop_chain")
mantra.render()
mantra = hou.node("/obj/render/rop_box")
mantra.render()
hou.hipFile.load("D:/HoudiniRender/test2.hiplc")
mantra = hou.node("/obj/render/rop_teapot")
mantra.render()